# Generated by Django 6.0.4 on 2026-04-29 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_studentanswer_actual_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testcase',
            name='setup_sql',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('text', 'Text Answer'), ('code', 'Coding Question'), ('sql', 'SQL Query Question')], default='mcq', max_length=20),
        ),
    ]
