# Generated by Django 6.0.4 on 2026-04-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_result_ip_address_result_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='access_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
